/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  paolo
 * Created: 19-mag-2016
 */

create table Utente 
(
    id_Utente Integer generated by default as identity primary key,
    nome varchar(128),
    cognome varchar(128),
    username varchar(128),
    password varchar(128),
    saldo double,
    identita boolean
);

create table Oggetto
(
    id_Oggetto Integer generated by default as identity primary key,
    nomeEAutore varchar(128),
    image varchar(128),
    descrizione varchar(400),
    prezzo double,
    quantita int
);

create table Oggetto_Utente
(
    id_Utente Integer,
    id_Oggetto Integer,
    FOREIGN KEY (id_Utente) REFERENCES Utente(id_Utente),
    FOREIGN KEY (id_Oggetto) REFERENCES Oggetto(id_Oggetto),
    PRIMARY KEY (id_Utente,id_Oggetto)
);

insert into Utente(id_Utente,nome,cognome,username,password,saldo,identita)
values(default,'Paolo','Corpino','paoloAmm','1',20,false),
(default,'Marco','Nic','marcoAmm','2',null,true);

insert into Oggetto(id_Oggetto,nomeEAutore,image,descrizione,prezzo,quantita)
values(default,'Sole - Emi Nava','img/sole.jpeg',null,18.0,3),
(default,'A spasso con il mostro - Julia Donaldson e Axel Scheffler','img/mostro.jpeg',null,6.0,3),
(default,'La chimera - Sebastiano Vassalli','img/chimera.jpeg',null,13.0,2),
(default,'A spasso con il mostro - Julia Donaldson e Axel Scheffler','img/mostro.jpeg',null,10.0,1),
(default,'Il mondo di Beatrix Potter - Beatrix Potter','img/mondo.jpeg',null,30.0,3);

insert into Oggetto_Utente(id_Utente,id_Oggetto)
values(1,1),(1,2),(1,3),(1,4),(1,5);